### PR TITLE
Ability to filter secret values from the backtrace.

### PR DESCRIPTION
**Pull request by svetlyak40wt**

### CODE REVIEW

**Comment by vindarel** [comment]
Very nice. Mention it in the README?

Best,

**Comment by vindarel** [comment]
(this PR is not closed, my comment was too quick then. Happy lisping!)

**Comment by svetlyak40wt** [comment]
@vindarel I'll add example into the README and will add a MGL-PAX documentation as soon as will refactor it (MGL-PAX) into two parts - minimal and builder.

**Comment by svetlyak40wt** [comment]
This will be the first project from this list https://40ants.com/projects.html which I'll try to move to GitHub Actions and MGL-PAX.

**Pull request merged**
